# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc394', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='note',
            field=models.CharField(default='na', max_length=250),
            preserve_default=False,
        ),
    ]
