# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc394', '0002_auto_20160402_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluation',
            old_name='votes',
            new_name='rank',
        ),
    ]
