# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc394', '0003_auto_20160504_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
