# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc394', '0005_auto_20160402_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer_url',
            field=models.URLField(blank=True),
        ),
    ]
