# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csc394', '0006_auto_20160515_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default=1, upload_to='main/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
