export var states = {
  INIT_STORE: 13,
  PRODUCT_UPDATE_SUCCESS: 1,
  PRODUCT_UPDATE_FAILED: 2,
  CREATE_USER_SUCCESS: 3,
  CREATE_USER_FAILED: 4,
  LOGIN_USER_SUCCESS: 5,
  LOGIN_USER_FAILED: 6,
  LOGOUT_USER_SUCCESS: 7,
  LOGOUT_USER_FAILED: 8,
  COMPANY_UPDATE_SUCCESS: 9,
  COMPANY_UPDATE_FAILED: 10,
  CREATE_COMPANY_SUCCESS: 11,
  CREATE_COMPANY_FAILED: 12
};

export var revStates = {};

for (let key of Object.keys(states)) {
  revStates[states[key]] = key;
};
